version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - sonar_network
    ports:
      - "8080:8080"
    environment:
      - SONARQUBE_URL=http://sonarqube:9000  # URL pour connecter Jenkins à SonarQube
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    networks:
      - sonar_network
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
  db:
    image: postgres:latest
    container_name: db
    networks:
      - sonar_network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  sonar_network:
    driver: bridge

volumes:
  db_data:
